### PR TITLE
Add mtools requirement and notify issue with older nasm

### PR DESCRIPTION
**Pull request by warpcoil**
Older versions of nasm have bug:

doslinux.asm:370: error: invalid combination of opcode and operands
doslinux.asm:372: error: invalid combination of opcode and operands
doslinux.asm:377: error: invalid combination of opcode and operands
doslinux.asm:379: error: invalid combination of opcode and operands
doslinux.asm:388: error: invalid combination of opcode and operands
doslinux.asm:390: error: invalid combination of opcode and operands

### CODE REVIEW

**Comment by haileys** [comment]
Thanks for letting me know about this nasm issue! I have fixed up the syntax in 45e86c29858017ef6e1360cdedd3f73ade602d1b to use a more compatible variant that should work on your version of nasm. Can you please check whether this now works?

**Comment by warpcoil** [comment]
Yes, I have reverted to the original version of nasm and I can confirm that works.  Absolutely awesome!

TODO:  Consider Adding DEBUG preprocessor guards on outb and inb, the whitelisted ports that aren't currently mapped print to screen or a /Q /Quiet command line option so we only get output relevant to us.

image

I am closing this issue.  Than k you so much!

**Comment by haileys** [comment]
> TODO: Consider Adding DEBUG preprocessor guards on outb and inb, the whitelisted ports that aren't currently mapped print to screen or a /Q /Quiet command line option so we only get output relevant to us.

This is a great suggestion. As of 54628ab146e66dde5f52dac0af6550c30f091000 DSL will start a serial console running a shell, so we could also send debug logging there

**Comment by warpcoil** [comment]
Perfection!

**Pull request closed without merging**
